module FortuneTeller
  module SpendingStrategy

    # The transforms generated by a spending strategy object
    class Transform < FortuneTeller::Base::Transform
      def initialize(holder:, date:, amount:)
        @amount = amount
        super(holder: holder, date: date)
      end

      def apply_to!(sim:)
        desired_debit = sim.inflate(amount: @amount, date: @date) - sim.guaranteed_take_home(date.year, date.month)
        sim.debit!(amount: desired_debit, date: date)
      end
    end
  end
end