module FortuneTeller
  module Job
    # The transforms generated by a job object
    class Transform < FortuneTeller::Base::Transform
      attr_reader :income

      def initialize(income:, account_credits:, **base)
        @income = income
        @account_credits = account_credits
        super(**base)
      end

      def apply_to(state)
        state.apply_w2_income(
          date: date,
          holder: holder,
          income: @income,
          account_credits: @account_credits
        )
      end
    end
  end
end