module FortuneTeller
  module Job
    # The transforms generated by a job object
    class Transform < FortuneTeller::Base::Transform
      attr_reader :income

      def initialize(account_credits:, **base)
        @account_credits = account_credits
        super(**base)
      end

      def apply_to!(sim:)
        @account_credits.each do |k, allocations|
          allocations.each do |holding, amount|
            grown_amount = sim.inflate(amount: amount, date: date)
            sim.credit_account!(key: k, holding: holding, date: date, amount: grown_amount)
          end
        end
      end
    end
  end
end