module FortuneTeller
  module SocialSecurity
    # The transforms generated by a social security object
    class Transform < FortuneTeller::Base::Transform
      def initialize(benefit:, **base)
        @benefit = benefit
        super(**base)
      end

      def apply_to(state)
        state.apply_ss_income(
          date: date,
          holder: holder,
          income: {ss: @benefit},
        )
      end
    end
  end
end